#!/usr/bin/env python3
"""Generate the user-facing CLI and tool inventory reference."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "generated" / "cli-and-tools.md"
sys.path.insert(0, str(ROOT))


def render() -> str:
    from networkforgeai.cli import build_parser
    from networkforgeai.tools import get_available_tools

    parser = build_parser()
    parser.prog = "networkforgeai"
    lines = [
        "# Generated CLI and Tool Reference",
        "",
        "> Generated by `tools/generate_cli_docs.py`. Do not edit this file manually.",
        "",
        "## Command-line options",
        "",
        "```text",
        parser.format_help().rstrip(),
        "```",
        "",
        "## Registered tools",
        "",
        "| Name | Risk | Category | Binary |",
        "|---|---|---|---|",
    ]
    for name, tool_class in sorted(get_available_tools().items()):
        lines.append(
            f"| `{name}` | `{tool_class.risk_level.value}` | "
            f"`{tool_class.category.value}` | `{tool_class.name}` |"
        )
    lines.extend(
        [
            "",
            "All high- and critical-risk tools require the approval gateway. Every scan also",
            "requires an explicit target scope. Use `--dry-run` to build commands without",
            "executing an external tool.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated output is stale")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"Generated documentation is stale: {OUTPUT}")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
